CDS-238 Fixed  incompatible combination of `notifications-python-client` and `pyjwt`
we need to increment the notification-python-client version; I was able to reproduce this error $SENTRY_URL/organizations/dit/issues/41715/ locally in my dnb virtualenv:

```
 I  (e) dnb-service  …  Ma  DI  dnb-service   master ✚ 1 … 4 ⚑ 8  python
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
 I >>> import jwt
 I >>> foo = jwt.encode(payload={'iss':'iamaclientid','iat':3131241232},key='iamsosecret',headers={'typ':'JWT','alg':'HS256'})
 I >>> foo.decode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'
```
Looks like pyjwt moved to returning ordinary strings from jwt.encode as of v2.0.0: https://pyjwt.readthedocs.io/en/stable/changelog.html#jwt-encode-return-type